services:
  web:
    image: pluswerk/php-dev:nginx-8.0
    volumes:
      - ./src:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.ssh:/home/application/.ssh
      - ~/.composer/cache:/home/application/.composer/cache
      - ~/.gitconfig:/home/application/.gitconfig
      - ../global/.docker/data/global-nginx-proxy/certs:/etc/nginx/certs:ro
      - ../global/.docker/config/global-nginx-proxy/additional_nginx.conf:/etc/nginx/conf.d/additional_nginx.conf
      - ../global/.docker/data/global-nginx-proxy/searchforcompose.conf:/etc/nginx/conf.d/searchforcompose.conf
    environment:
      #     Take a look at VIRTUAL_* in the documentation under Nginx Reverse Proxy
      - VIRTUAL_HOST=searchforcompose.${TLD_DOMAIN:?TLD_DOMAIN is required}
      - WEB_DOCUMENT_ROOT=/app/public

      - APPLICATION_UID=${APPLICATION_UID:-1000}
      - APPLICATION_GID=${APPLICATION_GID:-1000}
networks:
  default:
    name: global
    external: true